site_name: PySuSo
site_url: "https://mcneall.github.io/PySuSo/"
# This is the name of the branch that will be used by mike to commit versions of the documentation
remote_branch: docs 
extra:
  version:
    provider: mike
nav:
  - Getting Started: README.md
  - Examples: examples.md
  - Changelog: CHANGELOG.md
  - Licence: license.md
  - API:
    - Solvers: solvers.md
    - Boards: boards.md
    - Exceptions: exceptions.md

theme:
  name: material
  features:
    - content.code.copy

  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: orange
    accent: orange
    toggle:
      icon: material/lightbulb-outline
      name: "Switch to dark mode"
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: orange
    accent: orange
    toggle:
      icon: material/lightbulb
      name: "Switch to light mode"

watch:
  - src/pysuso

hooks:
  - docs/hooks/pysuso_hooks.py

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          import:
            - https://docs.python.org/3/objects.inv
          options:
            members_order: source
            separate_signature: true
            filters: ["!^_"]
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_signature_annotations: true
            signature_crossrefs: true
            docstring_style: google
            show_source: false
            show_symbol_type_toc: true
            show_symbol_type_heading: true
  - mike:
      version_selector: true
      canonical_version: latest

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      # use the inline style, otherwise line numbers do
      # not scale well
      linenums_style: pymdownx-inline
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
